### PR TITLE
Add FacialMorph Physics LiveSound Support.

### PR DESCRIPTION
**Pull request by croakfang**

### CODE REVIEW

**Comment by katboi01** [comment]
Impressive work, thank you for your contribution! I'm excited to see how facial morphs work, I wasn't able to figure out anything about them myself.
I see some features are not complete yet, and there is some test code leftover as well, I don't want to merge your pull request while it's still being worked on. Please let me know when it is safe for me to review your code, I will wait until then.

**Comment by croakfang** [comment]
Okay,  i will keep working on it.

**Comment by RabberDakk** [comment]
wow, the original shaders are working.
are there plans to add a game native ClothController? (not DB)
I wrote the source code halfway through, but could not get it to work...

**Comment by katboi01** [comment]
> Are there plans to add a game native ClothController? (not DB) I wrote the code of cloth halfway through, but could not get it to work...

I don't plan on adding new features myself, only maintain the viewer in case an update breaks it and add community contributions. Sorry...

**Comment by RabberDakk** [comment]
@croakfang Is development continuing? 
could you add an option to move the camera as well, if there is a related camera when the motion is played?

**Comment by croakfang** [comment]
@RabberDakk I have other things to work on and I haven't figured out a way to read the camera data correctly, so development is on hold for now, but I should continue this project in a while.

**Comment by RabberDakk** [comment]
@croakfang I'm looking forward to it! this patch is awesome and u guys coding skills are very advanced. If u guys open a patreon, I would 100% support this.

You guys may already know this, but I will share with u what I have known about camera. for example, below are probably the assets that make up the raceresult of chara 1037
[1037_raceresult.zip](https://github.com/katboi01/UmaViewer/files/9893038/1037_raceresult.zip)

|asset|detail|viewer supported|
|--|--|--|
|anm_res_chr1037_001.anim|body clip|✓|
|anm_res_chr1037_001_ear.anim|ear clip (via drivenkeylocator)||
|anm_res_chr1037_001_face.anim|facial clip (via drivenkeylocator)||
|anm_res_chr1037_001_cam.anim|camera clip||
|runtime_res_chr1037_001.json|camera fov? angle? initial position?||

the camera is particularly odd, something is missing from animationclip. perhaps cutt compensates for it. but my skills don't allow me to get more deepdive than this. Genius is needed 😭

**Comment by katboi01** [comment]
@croakfang Sorry for sleeping on this for so long, I've now added your and the community's contributions to the master branch (for "testing in production" 😉). I'm impressed by how much stuff you've added, if you want, I can add you as a collaborator so that you can push changes here without waiting for me in the future.
I will add some performance fixes and publish a build soon.

@RabberDakk Thank you for your support, but this isn't something we work on together, or regularily, to warrant a patreon. Though I can't promise I can do something about the camera, you should post the info you've gathered in the Issues tab of this repository, so that we have it for later.

**Pull request merged**
