### PR TITLE
Add manifest  reader to generate meta database. 

### PR DESCRIPTION
**Pull request by croakfang**
Umamusume uses the manifest file to generate meta database.  
It needs to download the root manifest file first, then recursively read the manifest file to get all resource directory. 
finally, insert all data into the meta database.

To download the latest root manifest, you must obtain the size and checksum of the root. 
Size and checksum can only be obtained through the msgpack package returned when log in to the game

### CODE REVIEW

**Comment by katboi01** [comment]
That's great! There is a file downloader ready on the DownloaderTest branch, maybe we could merge them.

**Comment by katboi01** [comment]
I ran UmaViewer, but I don't see the code used anywhere. Do we need something else to download the meta and manifest files?

**Comment by croakfang** [comment]
Yes, These codes have not been used by UmaViewer,  it requires the checksum and size of root to work.

If you want to test its function, you can get the size and checksum in the game's meta database
image

Then
```
ManifestDB db = new ManifestDB("mypath/meta");
db.GenerateMetaDB(77, 1541716412357448819);
```
This will generate the meta database of the current game resource version (may not be the latest)

Besides, I found that the game can request pre download to get these information without logging in, but the msgpack is encrypted, I am trying to decrypt these msgpack, so that the UmaViewer can run without the game client at all

**Comment by croakfang** [comment]
@katboi01 
It is difficult to decrypt the msgpack of the game,  so i use the SimpleSandman API to get root information now.
Click the Update Database button in UmaViewer to generate the latest meta and master databases.
image

**Pull request merged**
