### PR TITLE
Add morph name

### PR DESCRIPTION
**Pull request by CherishingWish**
Emotion presets are recorded in face_type_data which inside master.mdb, need to read sqlite database somehow...

### CODE REVIEW

**Comment by katboi01** [comment]
There is a built-in sql reader in the viewer, but it's very annoying to work with... I commited an update to master, you can now access face_type_data by using UmaDatabaseController.Instance.FaceTypeData.

**Comment by CherishingWish** [comment]
@katboi01 Thanks！I have manage to get this work now（but with a little duplicate code maybe...
Screenshot 2022-11-01 023618
Screenshot 2022-11-01 024303

**Comment by katboi01** [comment]
Changing the preset emotions is very laggy for me, I will look into making it a bit smoother.
I can't commit any changes to pull requests, because I don't have permission to use your repository. I added you two as collaborators, so that from now on you can create branches for new features and make pull requests from there.
If you prefer to work without branches, then maybe you could add me to your repository, so that I can submit my changes?

**Comment by katboi01** [comment]
image
I think something simple like this should be OK for now, until there is a faster solution. There are many emotions, so mixing them isn't necessary right now. And this works seamlessly, without any lag. What do you think?

Besides, I don't think current system works very well, some emotions work but others are broken.
image

**Comment by katboi01** [comment]
I undid Croakfang's "Merge duplicate code and optimize code" commit, and face posing works much better and doesn't have this problem. I think we should start over from there.

**Comment by CherishingWish** [comment]
wow, thank you for inviting us to your project！

And yes, there has some laggy because morph will all calculate again when single morph is change, so I change it to Update method after that......and CroakFang change it back. But I think he is working on a better solution now.

**Pull request merged**
